# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
- {name: 'Submissions', folder: 'pages', file: 'submissions.html'}
- {name: 'Issues', folder: 'pages', file: 'issues.html'}
- {name: 'Writer Spotlight', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Partners', folder: 'pages', file: 'partners.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/Crossroads-Magazine-1907290412725232/'}
- {icon: 'instagram', link: 'https://instagram.com/crossroadsmag'}
- {icon: 'envelope', link: 'mailto:crossroads.magazine.uvm@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
